name: taskify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  calendar_date_picker2: ^0.5.3
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  device_preview: ^1.1.0
  expandable: ^5.0.1
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_pin_code_fields: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mailer: ^6.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
